---
- name: Include platform-specific defaults
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"

- name: Include task file for Windows service start type
  ansible.builtin.include_tasks:
    file: "tasks/windows/shutdown-{{ swarm_client_windows_start_type }}.yml"
